/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ui.masterdata;

import javax.swing.ImageIcon;
import java.util.List;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.JOptionPane;
import java.awt.Color;
import java.awt.Component;
import java.awt.event.ActionEvent;
import java.awt.event.ItemEvent;
import java.awt.event.KeyEvent;
import java.time.LocalDate;
import java.time.temporal.ChronoUnit;
import javax.swing.AbstractAction;
import javax.swing.Action;
import javax.swing.ActionMap;
import javax.swing.InputMap;
import javax.swing.JComponent;
import javax.swing.JTable;
import javax.swing.KeyStroke;

import com.google.gson.JsonObject;
import masterdata.controllers.BatchController;
import models.dto.BatchDTO;
import models.dto.MaterialDTO;
import core.workers.BackgroundTask;
import ui.components.StatusMessageHandler;
import ui.dialogs.BatchStockViewForm;
import core.logging.Logger;

/**
 *
 * @author Sanod
 */
public class BatchManagementForm extends javax.swing.JFrame {

    private boolean isInitializing = true;
    private BatchController controller;
    private BatchDTO selectedBatch;
    private List<BatchDTO> allBatches = new ArrayList<>();
    private List<MaterialDTO> allMaterialsList = new ArrayList<>();
    private boolean isAddMode = false;
    private boolean isPopulating = false;

    /**
     * Creates new form BatchManagementForm
     */
    public BatchManagementForm() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setExtendedState(this.MAXIMIZED_BOTH);
        this.controller = new BatchController();
        setupTttFieldNavigation();
        setupKeyBindings();
        setupMaterialFilter();
        loadMaterials();
        loadBatchList();
        updateButtonStates();
        isInitializing = false;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtSearch = new javax.swing.JTextField();
        btnSearch = new javax.swing.JButton();
        btnRefresh = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        cmbMaterial = new ui.components.CheckedComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblBatches = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtBatchNo = new javax.swing.JTextField();
        txtSupplierBatchNo = new javax.swing.JTextField();
        cmbMaterialDetail = new javax.swing.JComboBox<>();
        cmbQualityStatus = new javax.swing.JComboBox<>();
        dcMfgDate = new com.toedter.calendar.JDateChooser();
        dcExpiryDate = new com.toedter.calendar.JDateChooser();
        jPanel2 = new javax.swing.JPanel();
        btnAdd = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnViewStock = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        txtStatus = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Batch Management");
        setIconImage(new ImageIcon(getClass().getResource("/icons/app-icon.png")).getImage());

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Search"));

        jLabel1.setText("Batch Number");

        btnSearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/btnicn/search-2-14.png"))); // NOI18N
        btnSearch.setText("  Search");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });

        btnRefresh.setIcon(new javax.swing.ImageIcon(getClass().getResource("/btnicn/sinchronize-14.png"))); // NOI18N
        btnRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshActionPerformed(evt);
            }
        });

        jLabel8.setText("Material Code");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cmbMaterial, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnRefresh, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnRefresh)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnSearch)
                        .addComponent(jLabel8)
                        .addComponent(cmbMaterial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        jScrollPane1.setBorder(javax.swing.BorderFactory.createTitledBorder("Batch List"));

        tblBatches.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Batch Number", "Supplier Batch", "Mfg Date", "Expiry Date", "Status", "Total Qty"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblBatches.setShowGrid(false);
        tblBatches.getTableHeader().setReorderingAllowed(false);
        tblBatches.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblBatchesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblBatches);

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Batch Details"));

        jLabel2.setText("Batch Number *");

        jLabel3.setText("Supplier Batch");

        jLabel4.setText("Manufacture Date");

        jLabel5.setText("Expiry Date");

        jLabel6.setText("Quality Status");

        jLabel9.setText("Material Code");

        cmbQualityStatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Released", "Quarantine", "Rejected" }));
        cmbQualityStatus.setSelectedIndex(-1);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addGap(18, 18, 18)
                        .addComponent(cmbMaterialDetail, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtBatchNo)
                            .addComponent(txtSupplierBatchNo)
                            .addComponent(dcMfgDate, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(dcExpiryDate, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(40, 40, 40)
                                .addComponent(jLabel6)
                                .addGap(10, 10, 10)
                                .addComponent(cmbQualityStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(555, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(cmbMaterialDetail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtBatchNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtSupplierBatchNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(dcMfgDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(dcExpiryDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(cmbQualityStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(40, Short.MAX_VALUE))
        );

        btnAdd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/btnicn/add-14.png"))); // NOI18N
        btnAdd.setText("Add Batch");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        btnUpdate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/btnicn/edit-14.png"))); // NOI18N
        btnUpdate.setText("  Update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        btnViewStock.setIcon(new javax.swing.ImageIcon(getClass().getResource("/btnicn/show-14.png"))); // NOI18N
        btnViewStock.setText("View Stock");
        btnViewStock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewStockActionPerformed(evt);
            }
        });

        btnClear.setIcon(new javax.swing.ImageIcon(getClass().getResource("/btnicn/clear_menu-14.png"))); // NOI18N
        btnClear.setText("  Clear");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });

        btnSave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/btnicn/save-14.png"))); // NOI18N
        btnSave.setText("  Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        jPanel5.setMaximumSize(new java.awt.Dimension(200, 22));
        jPanel5.setMinimumSize(new java.awt.Dimension(50, 22));
        jPanel5.setPreferredSize(new java.awt.Dimension(47, 22));

        txtStatus.setBackground(new java.awt.Color(255, 255, 255));
        txtStatus.setFont(new java.awt.Font("Segoe UI Semibold", 0, 11)); // NOI18N
        txtStatus.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtStatus.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtStatus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtStatus, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 22, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(btnAdd)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSave)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnClear)
                .addGap(37, 37, 37)
                .addComponent(btnUpdate)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnViewStock)
                .addGap(273, 273, 273)
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, 350, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnAdd)
                        .addComponent(btnUpdate)
                        .addComponent(btnViewStock)
                        .addComponent(btnClear)
                        .addComponent(btnSave))
                    .addComponent(jPanel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        loadMaterials();
        loadBatchList();
    }//GEN-LAST:event_formWindowOpened

    private void tblBatchesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblBatchesMouseClicked
        int selectedRow = tblBatches.getSelectedRow();
        if (selectedRow != -1) {
            String batchNo = (String) tblBatches.getValueAt(selectedRow, 0);
            selectedBatch = findBatchByNumber(batchNo);
            if (selectedBatch != null) {
                txtBatchNo.setText(selectedBatch.getBatchNumber());
                txtSupplierBatchNo.setText(selectedBatch.getSupplierBatch());
                if (selectedBatch.getManufactureDate() != null) {
                    dcMfgDate.setDate(java.sql.Date.valueOf(selectedBatch.getManufactureDate()));
                }
                if (selectedBatch.getExpiryDate() != null) {
                    dcExpiryDate.setDate(java.sql.Date.valueOf(selectedBatch.getExpiryDate()));
                }
                if (selectedBatch.getQualityStatus() != null) {
                    // Map DB uppercase enum to UI PascalCase
                    String uiStatus = dbStatusToUiStatus(selectedBatch.getQualityStatus());
                    cmbQualityStatus.setSelectedItem(uiStatus);
                }
                
                // Select matching material
                if (selectedBatch.getMaterialId() != null) {
                    int matchIdx = -1;
                    for (int i = 0; i < allMaterialsList.size(); i++) {
                        if (allMaterialsList.get(i).getMaterialId().equals(selectedBatch.getMaterialId())) {
                            matchIdx = i;
                            break;
                        }
                    }
                    cmbMaterialDetail.setSelectedIndex(matchIdx);
                } else {
                    cmbMaterialDetail.setSelectedIndex(-1);
                }
                
                isAddMode = false;
                updateButtonStates();
            }
        }
    }//GEN-LAST:event_tblBatchesMouseClicked

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        isAddMode = true;
        selectedBatch = null;
        clearForm();
        txtBatchNo.requestFocusInWindow();
        updateButtonStates();
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        if (!validateForm()) {
            return;
        }

        BatchDTO dto = new BatchDTO();
        dto.setBatchNumber(txtBatchNo.getText().trim());
        dto.setSupplierBatch(txtSupplierBatchNo.getText().trim());
        if (dcMfgDate.getDate() != null) {
            dto.setManufactureDate(new java.sql.Date(dcMfgDate.getDate().getTime()).toLocalDate());
        }
        if (dcExpiryDate.getDate() != null) {
            dto.setExpiryDate(new java.sql.Date(dcExpiryDate.getDate().getTime()).toLocalDate());
        }
        if (cmbQualityStatus.getSelectedIndex() >= 0) {
            dto.setQualityStatus(uiStatusToDbStatus(cmbQualityStatus.getSelectedItem().toString()));
        }
        int selectedMatIdx = cmbMaterialDetail.getSelectedIndex();
        if (selectedMatIdx >= 0 && selectedMatIdx < allMaterialsList.size()) {
            dto.setMaterialId(allMaterialsList.get(selectedMatIdx).getMaterialId());
        } else {
            StatusMessageHandler.showWarning(txtStatus, "Please select a material!");
            return;
        }

        BackgroundTask task = new BackgroundTask(this, "Saving Batch") {
            private int batchId;

            @Override
            protected Boolean performTask() throws Exception {
                updateProgress("Creating batch...");
                batchId = controller.createBatch(dto);
                return batchId > 0;
            }

            @Override
            protected void onSuccess() {
                StatusMessageHandler.showSuccess(txtStatus, "Batch created successfully!");
                clearForm();
                loadBatchList();
                updateButtonStates();
            }

            @Override
            protected void onFailure(Exception e) {
                StatusMessageHandler.showError(txtStatus, "Failed to create batch: " + e.getMessage());
            }
        };
        task.executeWithDialog();
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        clearForm();
        updateButtonStates();
    }//GEN-LAST:event_btnClearActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        if (!validateForm() || selectedBatch == null) {
            return;
        }

        selectedBatch.setBatchNumber(txtBatchNo.getText().trim());
        selectedBatch.setSupplierBatch(txtSupplierBatchNo.getText().trim());
        if (dcMfgDate.getDate() != null) {
            selectedBatch.setManufactureDate(new java.sql.Date(dcMfgDate.getDate().getTime()).toLocalDate());
        }
        if (dcExpiryDate.getDate() != null) {
            selectedBatch.setExpiryDate(new java.sql.Date(dcExpiryDate.getDate().getTime()).toLocalDate());
        }
        if (cmbQualityStatus.getSelectedIndex() >= 0) {
            selectedBatch.setQualityStatus(uiStatusToDbStatus(cmbQualityStatus.getSelectedItem().toString()));
        }
        int selectedMatIdx = cmbMaterialDetail.getSelectedIndex();
        if (selectedMatIdx >= 0 && selectedMatIdx < allMaterialsList.size()) {
            selectedBatch.setMaterialId(allMaterialsList.get(selectedMatIdx).getMaterialId());
        } else {
            StatusMessageHandler.showWarning(txtStatus, "Please select a material!");
            return;
        }

        BackgroundTask task = new BackgroundTask(this, "Updating Batch") {

            @Override
            protected Boolean performTask() throws Exception {
                updateProgress("Updating batch...");
                return controller.updateBatch(selectedBatch);
            }

            @Override
            protected void onSuccess() {
                StatusMessageHandler.showSuccess(txtStatus, "Batch updated successfully!");
                clearForm();
                loadBatchList();
                updateButtonStates();
            }

            @Override
            protected void onFailure(Exception e) {
                StatusMessageHandler.showError(txtStatus, "Failed to update batch: " + e.getMessage());
            }
        };
        task.executeWithDialog();
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        String searchTerm = txtSearch.getText().trim();
        if (searchTerm.isEmpty()) {
            loadBatchList();
            return;
        }

        BackgroundTask task = new BackgroundTask(this, "Searching Batches") {
            private List<BatchDTO> results;

            @Override
            protected Boolean performTask() throws Exception {
                updateProgress("Searching batches...");
                results = controller.searchBatches(searchTerm);
                return results != null;
            }

            @Override
            protected void onSuccess() {
                populateBatchTable(results);
            }

            @Override
            protected void onFailure(Exception e) {
                StatusMessageHandler.showError(txtStatus, "Search failed: " + e.getMessage());
            }
        };
        task.executeWithDialog();
    }//GEN-LAST:event_btnSearchActionPerformed

    private void btnRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshActionPerformed
        loadBatchList();
    }//GEN-LAST:event_btnRefreshActionPerformed

    private void btnViewStockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewStockActionPerformed
        if (selectedBatch == null || selectedBatch.getBatchId() == null) {
            StatusMessageHandler.showWarning(txtStatus, "Please select a batch first!");
            return;
        }

        BackgroundTask task = new BackgroundTask(this, "Loading Stock") {
            private List<JsonObject> stockData;

            @Override
            protected Boolean performTask() throws Exception {
                updateProgress("Fetching stock for batch " + selectedBatch.getBatchNumber() + "...");
                stockData = controller.getBatchStock(selectedBatch.getBatchId());
                return stockData != null;
            }

            @Override
            protected void onSuccess() {
                showStockDialog(stockData);
            }

            @Override
            protected void onFailure(Exception e) {
                StatusMessageHandler.showError(txtStatus, "Failed to load stock: " + e.getMessage());
            }
        };
        task.executeWithDialog();
    }//GEN-LAST:event_btnViewStockActionPerformed

    // deletes the selected batch after confirmation
    private void btnDeleteActionPerformed() {
        if (selectedBatch == null || selectedBatch.getBatchId() == null) {
            StatusMessageHandler.showWarning(txtStatus, "Please select a batch to delete!");
            return;
        }

        int confirm = JOptionPane.showConfirmDialog(this,
                "Are you sure you want to delete batch " + selectedBatch.getBatchNumber() + "?",
                "Confirm Delete", JOptionPane.YES_NO_OPTION);

        if (confirm != JOptionPane.YES_OPTION) {
            return;
        }

        BackgroundTask task = new BackgroundTask(this, "Deleting Batch") {
            @Override
            protected Boolean performTask() throws Exception {
                updateProgress("Deleting batch...");
                return controller.deleteBatch(selectedBatch.getBatchId());
            }

            @Override
            protected void onSuccess() {
                StatusMessageHandler.showSuccess(txtStatus, "Batch deleted successfully!");
                clearForm();
                loadBatchList();
                updateButtonStates();
            }

            @Override
            protected void onFailure(Exception e) {
                StatusMessageHandler.showError(txtStatus, "Failed to delete batch: " + e.getMessage());
            }
        };
        task.executeWithDialog();
    }

    // sets up material filter combo box listener

    private void setupMaterialFilter() {
        cmbMaterial.addActionListener((ActionEvent e) -> {
            if (!isPopulating) {
                onMaterialFilterSelected();
            }
        });
    }

    private void onMaterialFilterSelected() {
        java.util.Set<String> selected = cmbMaterial.getSelectedItems();
        if (selected.isEmpty()) {
            loadBatchList();
            return;
        }
        loadBatchesByMaterials(selected);
    }

    private void loadBatchesByMaterials(java.util.Set<String> selectedMaterialCodes) {
        BackgroundTask task = new BackgroundTask(this, "Loading Batches") {
            private List<BatchDTO> allResults = new ArrayList<>();

            @Override
            protected Boolean performTask() throws Exception {
                updateProgress("Fetching batches for materials...");
                java.util.Set<String> seenBatchNos = new java.util.HashSet<>();
                for (String code : selectedMaterialCodes) {
                    for (MaterialDTO mat : allMaterialsList) {
                        if (mat.getMaterialCode().equals(code)) {
                            List<BatchDTO> batches = controller.getBatchesByMaterial(mat.getMaterialId());
                            if (batches != null) {
                                for (BatchDTO b : batches) {
                                    if (seenBatchNos.add(b.getBatchNumber())) {
                                        allResults.add(b);
                                    }
                                }
                            }
                            break;
                        }
                    }
                }
                return true;
            }

            @Override
            protected void onSuccess() {
                populateBatchTable(allResults);
            }

            @Override
            protected void onFailure(Exception e) {
                StatusMessageHandler.showError(txtStatus, "Failed to load batches: " + e.getMessage());
            }
        };
        task.executeWithDialog();
    }

    private void loadMaterials() {
        while (true) {
            final boolean[] success = new boolean[1];
            final Exception[] error = new Exception[1];

            BackgroundTask task = new BackgroundTask(this, "Loading Materials") {
                private List<MaterialDTO> materialsList;

                @Override
                protected Boolean performTask() throws Exception {
                    updateProgress("Loading materials list...");
                    masterdata.controllers.MaterialController matController = new masterdata.controllers.MaterialController();
                    materialsList = matController.getAllMaterials();
                    return materialsList != null;
                }

                @Override
                protected void onSuccess() {
                    // Filter to only batch-managed materials
                    List<MaterialDTO> batchManagedMaterials = new ArrayList<>();
                    if (materialsList != null) {
                        for (MaterialDTO mat : materialsList) {
                            if (mat.isBatchManaged()) {
                                batchManagedMaterials.add(mat);
                            }
                        }
                    }
                    allMaterialsList = batchManagedMaterials;

                    isPopulating = true;
                    try {
                        // Populate cmbMaterial (filter)
                        cmbMaterial.removeAllItems();
                        cmbMaterial.setSelectAllLabel("All");
                        cmbMaterial.addItem("All");
                        for (MaterialDTO mat : allMaterialsList) {
                            cmbMaterial.addItem(mat.getMaterialCode());
                        }

                        // Populate cmbMaterialDetail
                        cmbMaterialDetail.removeAllItems();
                        for (MaterialDTO mat : allMaterialsList) {
                            cmbMaterialDetail.addItem(mat.getMaterialCode() + " - " + mat.getMaterialDescription());
                        }
                        cmbMaterialDetail.setSelectedIndex(-1);
                    } finally {
                        isPopulating = false;
                    }
                    success[0] = true;
                }

                @Override
                protected void onFailure(Exception e) {
                    error[0] = e;
                }
            };
            task.executeWithDialog();

            if (success[0]) {
                break;
            } else {
                Object[] options = {"Retry", "Exit"};
                int choice = JOptionPane.showOptionDialog(
                        this,
                        "Failed to load materials: " + (error[0] != null ? error[0].getMessage() : "Unknown error") + "\nPlease check and try again!",
                        "Loading Failed",
                        JOptionPane.DEFAULT_OPTION,
                        JOptionPane.ERROR_MESSAGE,
                        null,
                        options,
                        options[0]
                );
                if (choice != 0) {
                    if (isInitializing) {
                        dispose();
                        throw new RuntimeException("Cancelled form loading due to fetch failure.");
                    } else {
                        StatusMessageHandler.showError(txtStatus, "Failed to load materials!");
                        break;
                    }
                }
            }
        }
    }

    private void setupTttFieldNavigation() {
        javax.swing.JTextField[] textFields = {txtSearch, txtBatchNo, txtSupplierBatchNo};

        for (int i = 0; i < textFields.length; i++) {
            final int currentIndex = i;
            textFields[i].addKeyListener(new java.awt.event.KeyAdapter() {
                @Override
                public void keyPressed(java.awt.event.KeyEvent evt) {
                    if (evt.getKeyCode() == java.awt.event.KeyEvent.VK_DOWN) {
                        evt.consume();
                        if (currentIndex < textFields.length - 1) {
                            textFields[currentIndex + 1].requestFocus();
                        }
                    } else if (evt.getKeyCode() == java.awt.event.KeyEvent.VK_UP) {
                        evt.consume();
                        if (currentIndex > 0) {
                            textFields[currentIndex - 1].requestFocus();
                        }
                    }
                }
            });
        }
    }

    private void setupKeyBindings() {
        InputMap inputMap = getRootPane().getInputMap(JComponent.WHEN_IN_FOCUSED_WINDOW);
        ActionMap actionMap = getRootPane().getActionMap();

        Action addAction = new AbstractAction() {
            @Override
            public void actionPerformed(ActionEvent e) {
                if (btnAdd.isEnabled()) btnAdd.doClick();
            }
        };

        Action saveAction = new AbstractAction() {
            @Override
            public void actionPerformed(ActionEvent e) {
                if (btnSave.isEnabled()) btnSave.doClick();
            }
        };

        Action clearAction = new AbstractAction() {
            @Override
            public void actionPerformed(ActionEvent e) {
                if (btnClear.isEnabled()) btnClear.doClick();
            }
        };

        Action updateAction = new AbstractAction() {
            @Override
            public void actionPerformed(ActionEvent e) {
                if (btnUpdate.isEnabled()) btnUpdate.doClick();
            }
        };

        Action deleteAction = new AbstractAction() {
            @Override
            public void actionPerformed(ActionEvent e) {
                btnDeleteActionPerformed();
            }
        };

        Action refreshAction = new AbstractAction() {
            @Override
            public void actionPerformed(ActionEvent e) {
                if (btnRefresh.isEnabled()) btnRefresh.doClick();
            }
        };

        Action searchAction = new AbstractAction() {
            @Override
            public void actionPerformed(ActionEvent e) {
                if (btnSearch.isEnabled()) btnSearch.doClick();
            }
        };

        inputMap.put(KeyStroke.getKeyStroke(KeyEvent.VK_N, ActionEvent.ALT_MASK), "add");
        inputMap.put(KeyStroke.getKeyStroke(KeyEvent.VK_F6, 0), "addF6");
        actionMap.put("add", addAction);
        actionMap.put("addF6", addAction);

        inputMap.put(KeyStroke.getKeyStroke(KeyEvent.VK_S, ActionEvent.ALT_MASK), "save");
        inputMap.put(KeyStroke.getKeyStroke(KeyEvent.VK_F7, 0), "saveF7");
        actionMap.put("save", saveAction);
        actionMap.put("saveF7", saveAction);

        inputMap.put(KeyStroke.getKeyStroke(KeyEvent.VK_C, ActionEvent.ALT_MASK), "clear");
        inputMap.put(KeyStroke.getKeyStroke(KeyEvent.VK_F8, 0), "clearF8");
        actionMap.put("clear", clearAction);
        actionMap.put("clearF8", clearAction);

        inputMap.put(KeyStroke.getKeyStroke(KeyEvent.VK_U, ActionEvent.ALT_MASK), "update");
        inputMap.put(KeyStroke.getKeyStroke(KeyEvent.VK_F9, 0), "updateF9");
        actionMap.put("update", updateAction);
        actionMap.put("updateF9", updateAction);

        inputMap.put(KeyStroke.getKeyStroke(KeyEvent.VK_D, ActionEvent.ALT_MASK), "delete");
        inputMap.put(KeyStroke.getKeyStroke(KeyEvent.VK_F10, 0), "deleteF10");
        actionMap.put("delete", deleteAction);
        actionMap.put("deleteF10", deleteAction);

        inputMap.put(KeyStroke.getKeyStroke(KeyEvent.VK_R, ActionEvent.ALT_MASK), "refresh");
        actionMap.put("refresh", refreshAction);

        inputMap.put(KeyStroke.getKeyStroke(KeyEvent.VK_Q, ActionEvent.ALT_MASK), "search");
        actionMap.put("search", searchAction);
    }

    // loads and populates batch data into the table

    private void loadBatchList() {
        while (true) {
            final boolean[] success = new boolean[1];
            final Exception[] error = new Exception[1];

            BackgroundTask task = new BackgroundTask(this, "Loading Batches") {
                private List<BatchDTO> batches;

                @Override
                protected Boolean performTask() throws Exception {
                    updateProgress("Fetching batches...");
                    batches = controller.getAllBatches();
                    return batches != null;
                }

                @Override
                protected void onSuccess() {
                    populateBatchTable(batches);
                    success[0] = true;
                }

                @Override
                protected void onFailure(Exception e) {
                    error[0] = e;
                }
            };
            task.executeWithDialog();

            if (success[0]) {
                break;
            } else {
                Object[] options = {"Retry", "Exit"};
                int choice = JOptionPane.showOptionDialog(
                        this,
                        "Failed to load batches: " + (error[0] != null ? error[0].getMessage() : "Unknown error") + "\nPlease check and try again!",
                        "Loading Failed",
                        JOptionPane.DEFAULT_OPTION,
                        JOptionPane.ERROR_MESSAGE,
                        null,
                        options,
                        options[0]
                );
                if (choice != 0) {
                    if (isInitializing) {
                        dispose();
                        throw new RuntimeException("Cancelled form loading due to fetch failure.");
                    } else {
                        StatusMessageHandler.showError(txtStatus, "Failed to load batches!");
                        break;
                    }
                }
            }
        }
    }

    private void populateBatchTable(List<BatchDTO> batches) {
        this.allBatches = batches;
        DefaultTableModel model = new DefaultTableModel(
            new String[] {"Batch Number", "Supplier Batch", "Mfg Date", "Expiry Date", "Status", "Days to Expiry"},
            0
        ) {
            @Override
            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return false;
            }
        };

        if (batches != null) {
            for (BatchDTO b : batches) {
                String statusDisplay = b.getQualityStatus() != null
                        ? dbStatusToUiStatus(b.getQualityStatus()) : "";

                String daysDisplay = "";
                if (b.getExpiryDate() != null) {
                    long days = ChronoUnit.DAYS.between(LocalDate.now(), b.getExpiryDate());
                    if (days <= 0) {
                        daysDisplay = "EXPIRED";
                    } else {
                        daysDisplay = days + " days";
                    }
                } else {
                    daysDisplay = "N/A";
                }

                model.addRow(new Object[]{
                    b.getBatchNumber(),
                    b.getSupplierBatch() != null ? b.getSupplierBatch() : "",
                    b.getManufactureDate() != null ? b.getManufactureDate().toString() : "",
                    b.getExpiryDate() != null ? b.getExpiryDate().toString() : "",
                    statusDisplay,
                    daysDisplay
                });
            }
        }

        tblBatches.setModel(model);
        tblBatches.getTableHeader().setReorderingAllowed(false);

        // Apply expiry color coding
        applyExpiryColorCoding();
    }

    // color-codes rows by expiry: red = expired, yellow = expiring within 30 days
    private void applyExpiryColorCoding() {
        tblBatches.setDefaultRenderer(Object.class, new DefaultTableCellRenderer() {
            private final Color EXPIRED_BG = new Color(255, 210, 210);          // Soft red
            private final Color EXPIRED_FG = new Color(180, 0, 0);              // Dark red text
            private final Color EXPIRING_SOON_BG = new Color(255, 248, 200);    // Soft yellow
            private final Color EXPIRING_SOON_FG = new Color(140, 100, 0);      // Dark amber text
            private final Color NORMAL_BG = Color.WHITE;
            private final Color NORMAL_FG = Color.BLACK;

            @Override
            public Component getTableCellRendererComponent(JTable table, Object value,
                    boolean isSelected, boolean hasFocus, int row, int column) {
                Component c = super.getTableCellRendererComponent(table, value, isSelected, hasFocus, row, column);

                if (!isSelected) {
                    // Default
                    c.setBackground(NORMAL_BG);
                    c.setForeground(NORMAL_FG);

                    if (row < allBatches.size()) {
                        BatchDTO batch = allBatches.get(row);
                        if (batch.getExpiryDate() != null) {
                            long daysToExpiry = ChronoUnit.DAYS.between(LocalDate.now(), batch.getExpiryDate());
                            if (daysToExpiry <= 0) {
                                c.setBackground(EXPIRED_BG);
                                c.setForeground(EXPIRED_FG);
                            } else if (daysToExpiry <= 30) {
                                c.setBackground(EXPIRING_SOON_BG);
                                c.setForeground(EXPIRING_SOON_FG);
                            }
                        }
                    }
                }
                return c;
            }
        });
        tblBatches.repaint();
    }

    private BatchDTO findBatchByNumber(String batchNo) {
        if (batchNo == null || allBatches == null) return null;
        for (BatchDTO b : allBatches) {
            if (b.getBatchNumber().equals(batchNo)) return b;
        }
        return null;
    }

    private boolean validateForm() {
        // Check batch number is provided
        if (txtBatchNo.getText().trim().isEmpty()) {
            StatusMessageHandler.showWarning(txtStatus, "Batch number is required!");
            txtBatchNo.requestFocusInWindow();
            return false;
        }

        // Check material is selected
        if (cmbMaterialDetail.getSelectedIndex() < 0) {
            StatusMessageHandler.showWarning(txtStatus, "Please select a material!");
            cmbMaterialDetail.requestFocusInWindow();
            return false;
        }

        // Check quality status is selected
        if (cmbQualityStatus.getSelectedIndex() < 0) {
            StatusMessageHandler.showWarning(txtStatus, "Please select a quality status!");
            cmbQualityStatus.requestFocusInWindow();
            return false;
        }

        // Validate dates: if both are set, expiry must be after manufacture
        if (dcMfgDate.getDate() != null && dcExpiryDate.getDate() != null) {
            if (!dcExpiryDate.getDate().after(dcMfgDate.getDate())) {
                StatusMessageHandler.showWarning(txtStatus, "Expiry date must be after manufacture date!");
                dcExpiryDate.requestFocusInWindow();
                return false;
            }
        }

        return true;
    }

    private void clearForm() {
        txtBatchNo.setText("");
        txtSupplierBatchNo.setText("");
        dcMfgDate.setDate(null);
        dcExpiryDate.setDate(null);
        cmbQualityStatus.setSelectedIndex(-1);
        cmbMaterialDetail.setSelectedIndex(-1);
        selectedBatch = null;
        tblBatches.clearSelection();
        isAddMode = false;
    }

    private void updateButtonStates() {
        btnAdd.setEnabled(!isAddMode && selectedBatch == null);
        btnSave.setEnabled(isAddMode);
        btnClear.setEnabled(isAddMode || selectedBatch != null);
        btnUpdate.setEnabled(selectedBatch != null && !isAddMode);
    }

    // maps DB uppercase status to UI display format

    /**
     * Map DB uppercase enum (RELEASED, QUARANTINE, REJECTED) to UI PascalCase.
     */
    private String dbStatusToUiStatus(String dbStatus) {
        if (dbStatus == null) return "";
        switch (dbStatus.toUpperCase()) {
            case "RELEASED":   return "Released";
            case "QUARANTINE": return "Quarantine";
            case "REJECTED":   return "Rejected";
            default:           return dbStatus;
        }
    }

    /**
     * Map UI PascalCase to DB uppercase enum.
     */
    private String uiStatusToDbStatus(String uiStatus) {
        if (uiStatus == null) return "RELEASED";
        switch (uiStatus) {
            case "Released":   return "RELEASED";
            case "Quarantine": return "QUARANTINE";
            case "Rejected":   return "REJECTED";
            default:           return uiStatus.toUpperCase();
        }
    }

    // opens batch stock view dialog

    private void showStockDialog(List<JsonObject> stockData) {
        BatchStockViewForm dialog = new BatchStockViewForm(this, true, selectedBatch, stockData);
        dialog.setVisible(true);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnRefresh;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnSearch;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JButton btnViewStock;
    private ui.components.CheckedComboBox<String> cmbMaterial;
    private javax.swing.JComboBox<String> cmbMaterialDetail;
    private javax.swing.JComboBox<String> cmbQualityStatus;
    private com.toedter.calendar.JDateChooser dcExpiryDate;
    private com.toedter.calendar.JDateChooser dcMfgDate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblBatches;
    private javax.swing.JTextField txtBatchNo;
    private javax.swing.JTextField txtSearch;
    private javax.swing.JLabel txtStatus;
    private javax.swing.JTextField txtSupplierBatchNo;
    // End of variables declaration//GEN-END:variables
}
