/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ui;

import core.security.*;
import javax.swing.ImageIcon;
import javax.swing.tree.DefaultMutableTreeNode;
import java.util.Map;

import ui.components.*;
import ui.masterdata.*;
import ui.movements.*;
import ui.reports.*;
import ui.inventory.*;

import java.awt.event.ActionEvent;
import java.awt.event.InputEvent;
import java.awt.event.KeyEvent;
import javax.swing.AbstractAction;
import javax.swing.Action;
import javax.swing.ActionMap;
import javax.swing.InputMap;
import javax.swing.JComponent;
import javax.swing.JOptionPane;
import javax.swing.KeyStroke;
import java.awt.event.InputEvent;
import models.entity.User;

/**
 *
 * @author Sanod
 */
public class MainFrame extends javax.swing.JFrame {

    private final UserSession userSession;

    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setExtendedState(this.MAXIMIZED_BOTH);

        // init user session
        userSession = UserSession.getInstance();
        if (userSession.isValid()) {
            User.UserRole userRole = userSession.getUserRole();

            if (userRole == User.UserRole.ADMIN) {
                btnUser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/admin.png")));
            } else if (userRole == User.UserRole.SUPERVISOR) {
                btnUser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/supervisor.png")));
            } else if (userRole == User.UserRole.OPERATOR) {
                btnUser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/operator.png")));
            } else if (userRole == User.UserRole.MANAGER) {
                btnUser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/manager.png")));
            }

            btnUser.setText("   " + userSession.getUsername());
        }

        setupKeyBindings();

        // hide What's New content by default (accordion collapsed)
        pnlWhatsNewContent.setVisible(false);
    }
    
    private void setupKeyBindings() {
        InputMap inputMap = getRootPane().getInputMap(JComponent.WHEN_IN_FOCUSED_WINDOW);
        ActionMap actionMap = getRootPane().getActionMap();

        Action altSAction = new AbstractAction() {
            @Override
            public void actionPerformed(ActionEvent e) {
                btnConfirm.doClick();
            }
        };

        Action f10Action = new AbstractAction() {
            @Override
            public void actionPerformed(ActionEvent e) {
                btnConfirm.doClick();
            }
        };

        KeyStroke altS = KeyStroke.getKeyStroke(KeyEvent.VK_S, InputEvent.ALT_DOWN_MASK);
        KeyStroke f10 = KeyStroke.getKeyStroke(KeyEvent.VK_F10, 0);

        inputMap.put(altS, "altSConfirm");
        actionMap.put("altSConfirm", altSAction);

        inputMap.put(f10, "f10Confirm");
        actionMap.put("f10Confirm", f10Action);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        popupUserBtn = new javax.swing.JPopupMenu();
        menuitemLogout = new javax.swing.JMenuItem();
        jScrollPane1 = new javax.swing.JScrollPane();
        treeMovement = new javax.swing.JTree();
        cmbMovement = new javax.swing.JComboBox<>();
        btnConfirm = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        txtStatus = new javax.swing.JLabel();
        btnUser = new javax.swing.JButton();
        pnlWelcome = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnWhatsNewToggle = new javax.swing.JButton();
        pnlWhatsNewContent = new javax.swing.JPanel();
        lblUpdate1Title = new javax.swing.JLabel();
        lblUpdate1Desc = new javax.swing.JLabel();
        lblUpdate2Title = new javax.swing.JLabel();
        lblUpdate2Desc = new javax.swing.JLabel();
        lblUpdate3Title = new javax.swing.JLabel();
        lblUpdate3Desc = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        pnlCap1 = new javax.swing.JPanel();
        lblCap1Title = new javax.swing.JLabel();
        lblCap1Desc = new javax.swing.JLabel();
        pnlCap2 = new javax.swing.JPanel();
        lblCap2Title = new javax.swing.JLabel();
        lblCap2Desc = new javax.swing.JLabel();
        pnlCap3 = new javax.swing.JPanel();
        lblCap3Title = new javax.swing.JLabel();
        lblCap3Desc = new javax.swing.JLabel();
        pnlCap4 = new javax.swing.JPanel();
        lblCap4Title = new javax.swing.JLabel();
        lblCap4Desc = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        mitemLogout = new javax.swing.JMenuItem();

        popupUserBtn.setPreferredSize(new java.awt.Dimension(140, 30));

        menuitemLogout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/btnicn/logout-14.png"))); // NOI18N
        menuitemLogout.setText("  Logout");
        menuitemLogout.setMaximumSize(new java.awt.Dimension(140, 28));
        menuitemLogout.setMinimumSize(new java.awt.Dimension(140, 28));
        menuitemLogout.setPreferredSize(new java.awt.Dimension(140, 22));
        menuitemLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuitemLogoutActionPerformed(evt);
            }
        });
        popupUserBtn.add(menuitemLogout);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImage(new ImageIcon(getClass().getResource("/icons/app-icon.png")).getImage());
        setMinimumSize(new java.awt.Dimension(900, 600));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        javax.swing.tree.DefaultMutableTreeNode treeNode1 = new javax.swing.tree.DefaultMutableTreeNode("Warehouse Management System");
        javax.swing.tree.DefaultMutableTreeNode treeNode2 = new javax.swing.tree.DefaultMutableTreeNode("Master Data");
        javax.swing.tree.DefaultMutableTreeNode treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("MD31 - Material Master");
        treeNode2.add(treeNode3);
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("MD32 - Batch Management");
        treeNode2.add(treeNode3);
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("MD33 - Bin Management");
        treeNode2.add(treeNode3);
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("MD34 - Zone Management");
        treeNode2.add(treeNode3);
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("MD35 - Vendor");
        treeNode2.add(treeNode3);
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("MD36 - Customer");
        treeNode2.add(treeNode3);
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("MD37 - UOM");
        treeNode2.add(treeNode3);
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("MD38 - User Management");
        treeNode2.add(treeNode3);
        treeNode1.add(treeNode2);
        treeNode2 = new javax.swing.tree.DefaultMutableTreeNode("Inbound");
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("IN11 - GR Purchase Order");
        treeNode2.add(treeNode3);
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("IN12 - GR Customer Returns");
        treeNode2.add(treeNode3);
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("IN13 - GR Transfer In");
        treeNode2.add(treeNode3);
        treeNode1.add(treeNode2);
        treeNode2 = new javax.swing.tree.DefaultMutableTreeNode("Outbound");
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("OUT14 - GI Sales Order");
        treeNode2.add(treeNode3);
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("OUT15 - Return to Vendor");
        treeNode2.add(treeNode3);
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("OUT16 - GI Internal Consumption");
        treeNode2.add(treeNode3);
        treeNode1.add(treeNode2);
        treeNode2 = new javax.swing.tree.DefaultMutableTreeNode("Internal");
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("INT17 - Bin-to-Bin Transfer");
        treeNode2.add(treeNode3);
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("INT18 - Splitting/Pack Break");
        treeNode2.add(treeNode3);
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("INT19 - Cycle Count");
        treeNode2.add(treeNode3);
        treeNode1.add(treeNode2);
        treeNode2 = new javax.swing.tree.DefaultMutableTreeNode("Adjustments");
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("ADJ20 - Inventory Adjustment");
        treeNode2.add(treeNode3);
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("ADJ21 - Scrap Write-off");
        treeNode2.add(treeNode3);
        treeNode1.add(treeNode2);
        treeNode2 = new javax.swing.tree.DefaultMutableTreeNode("Transfer");
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("TR22 - Putaway TO");
        treeNode2.add(treeNode3);
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("TR23 - Picking TO");
        treeNode2.add(treeNode3);
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("TR24 - Replenishment TO");
        treeNode2.add(treeNode3);
        treeNode1.add(treeNode2);
        treeNode2 = new javax.swing.tree.DefaultMutableTreeNode("Queries");
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("INV51 - Inventory Query");
        treeNode2.add(treeNode3);
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("INV52 - Stock Overview");
        treeNode2.add(treeNode3);
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("INV53 - Batch Tracking");
        treeNode2.add(treeNode3);
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("INV54 - Stock Level");
        treeNode2.add(treeNode3);
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("INV55 - Expiry Monitor");
        treeNode2.add(treeNode3);
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("INV56 - Inventory Alerts");
        treeNode2.add(treeNode3);
        treeNode1.add(treeNode2);
        treeNode2 = new javax.swing.tree.DefaultMutableTreeNode("Reports");
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("REP61 - Daily Activity");
        treeNode2.add(treeNode3);
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("REP62 - Inventory Valuation");
        treeNode2.add(treeNode3);
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("REP63 - Stock Aging");
        treeNode2.add(treeNode3);
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("REP64 - Performance Report");
        treeNode2.add(treeNode3);
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("REP65 - Utilization Report");
        treeNode2.add(treeNode3);
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("REP66 - Financial Report");
        treeNode2.add(treeNode3);
        treeNode1.add(treeNode2);
        treeMovement.setModel(new javax.swing.tree.DefaultTreeModel(treeNode1));
        treeMovement.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                treeMovementMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(treeMovement);

        cmbMovement.setEditable(true);
        cmbMovement.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "MD31 - Material Master", "MD32 - Batch Management", "MD33 - Bin Management", "MD34 - Zone Management", "MD35 - Vendor", "MD36 - Customer", "MD37 - UOM", "MD38 - User Management", "IN11 - GR Purchase Order", "IN12 - GR Customer Returns", "IN13 - GR Transfer In", "OUT14 - GI Sales Order", "OUT15 - Return to Vendor", "OUT16 - GI Internal Consumption", "INT17 - Bin-to-Bin Transfer", "INT18 - Splitting/Pack Break", "INT19 - Cycle Count", "ADJ20 - Inventory Adjustment", "ADJ21 - Scrap Write-off", "TR22 - Putaway TO", "TR23 - Picking TO", "TR24 - Replenishment TO", "INV51 - Inventory Query", "INV52 - Stock Overview", "INV53 - Batch Tracking", "INV54 - Stock Level", "INV55 - Expiry Monitor", "INV56 - Inventory Alerts", "REP61 - Daily Activity", "REP62 - Inventory Valuation", "REP63 - Stock Aging", "REP64 - Performance Report", "REP65 - Utilization Report", "REP66 - Financial Report" }));
        cmbMovement.setSelectedIndex(-1);
        cmbMovement.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cmbMovementKeyPressed(evt);
            }
        });

        btnConfirm.setIcon(new javax.swing.ImageIcon(getClass().getResource("/black-done.png"))); // NOI18N
        btnConfirm.setMnemonic('S');
        btnConfirm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmActionPerformed(evt);
            }
        });

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/black-support.png"))); // NOI18N
        jButton3.setText("Help & Support");

        jPanel5.setMaximumSize(new java.awt.Dimension(200, 22));
        jPanel5.setMinimumSize(new java.awt.Dimension(50, 22));
        jPanel5.setPreferredSize(new java.awt.Dimension(47, 22));

        txtStatus.setBackground(new java.awt.Color(255, 255, 255));
        txtStatus.setFont(new java.awt.Font("Segoe UI Semibold", 0, 11)); // NOI18N
        txtStatus.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtStatus.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtStatus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtStatus, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 22, Short.MAX_VALUE)
        );

        btnUser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/admin.png"))); // NOI18N
        btnUser.setText("  Username");
        btnUser.setMaximumSize(new java.awt.Dimension(140, 28));
        btnUser.setMinimumSize(new java.awt.Dimension(140, 28));
        btnUser.setPreferredSize(new java.awt.Dimension(140, 28));
        btnUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUserActionPerformed(evt);
            }
        });

        pnlWelcome.setBackground(new java.awt.Color(255, 255, 255));
        pnlWelcome.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(100, 116, 139));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/logo-28.png"))); // NOI18N
        jLabel1.setText("FYUXERA");

        jLabel2.setFont(new java.awt.Font("Segoe UI Semibold", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(15, 23, 42));
        jLabel2.setText("Welcome to Hivon");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(100, 116, 139));
        jLabel3.setText("WAREHOUSE MANAGEMENT SYSTEM");

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(71, 85, 105));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel4.setText("<html> <div style='width:250px'> Hivon is a secure, enterprise-grade warehouse management platform designed to optimize daily stock tracking, streamline goods movements, and maintain accurate inventory control across physical locations. </div> </html>");
        jLabel4.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jLabel4.setFocusable(false);
        jLabel4.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jLabel4.setVerticalTextPosition(javax.swing.SwingConstants.TOP);

        btnWhatsNewToggle.setText("<html><b>What's new</b><br><font size='2' color='#64748B'>Latest updates in Hivon WMS</font></html>");
        btnWhatsNewToggle.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnWhatsNewToggle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnWhatsNewToggleActionPerformed(evt);
            }
        });

        pnlWhatsNewContent.setBackground(new java.awt.Color(255, 255, 255));

        lblUpdate1Title.setFont(new java.awt.Font("Segoe UI Semibold", 0, 11)); // NOI18N
        lblUpdate1Title.setText("Auto-Calculated Putaway Suggestion (June 2026)");

        lblUpdate1Desc.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        lblUpdate1Desc.setForeground(new java.awt.Color(71, 85, 105));
        lblUpdate1Desc.setText("<html><div style='width:250px'>The system now automatically suggests optimal storage bins upon goods receipt, preventing capacity overload and optimizing rack configuration.</div></html>");

        lblUpdate2Title.setFont(new java.awt.Font("Segoe UI Semibold", 0, 11)); // NOI18N
        lblUpdate2Title.setText("FEFO Stock Picking Priority (May 2026)");

        lblUpdate2Desc.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        lblUpdate2Desc.setForeground(new java.awt.Color(71, 85, 105));
        lblUpdate2Desc.setText("<html><div style='width:250px'>Picking lists automatically prioritize batches closest to their expiry date first, drastically reducing material waste in perishable lines.</div></html>");

        lblUpdate3Title.setFont(new java.awt.Font("Segoe UI Semibold", 0, 11)); // NOI18N
        lblUpdate3Title.setText("Real-Time Inventory Adjustment Approvals (April 2026)");

        lblUpdate3Desc.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        lblUpdate3Desc.setForeground(new java.awt.Color(71, 85, 105));
        lblUpdate3Desc.setText("<html><div style='width:250px'>Supervisors can now authorize count discrepancies directly from the floor, adjusting inventory valuation immediately in the central database.</div></html>");

        javax.swing.GroupLayout pnlWhatsNewContentLayout = new javax.swing.GroupLayout(pnlWhatsNewContent);
        pnlWhatsNewContent.setLayout(pnlWhatsNewContentLayout);
        pnlWhatsNewContentLayout.setHorizontalGroup(
            pnlWhatsNewContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlWhatsNewContentLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlWhatsNewContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblUpdate1Title)
                    .addComponent(lblUpdate1Desc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblUpdate2Title)
                    .addComponent(lblUpdate2Desc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblUpdate3Title)
                    .addComponent(lblUpdate3Desc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlWhatsNewContentLayout.setVerticalGroup(
            pnlWhatsNewContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlWhatsNewContentLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblUpdate1Title)
                .addGap(2, 2, 2)
                .addComponent(lblUpdate1Desc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(lblUpdate2Title)
                .addGap(2, 2, 2)
                .addComponent(lblUpdate2Desc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(lblUpdate3Title)
                .addGap(2, 2, 2)
                .addComponent(lblUpdate3Desc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel5.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(100, 116, 139));
        jLabel5.setText("CORE CAPABILITIES");

        pnlCap1.setBackground(new java.awt.Color(255, 255, 255));
        pnlCap1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        lblCap1Title.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        lblCap1Title.setText("INBOUND & OUTBOUND LOGISTICS");

        lblCap1Desc.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        lblCap1Desc.setForeground(new java.awt.Color(100, 116, 139));
        lblCap1Desc.setText("<html><div style='width:250px'>Manages standard goods receipts from purchase orders, picking workflows for customer sales orders, inbound returns, and supplier returns.</div></html>");

        javax.swing.GroupLayout pnlCap1Layout = new javax.swing.GroupLayout(pnlCap1);
        pnlCap1.setLayout(pnlCap1Layout);
        pnlCap1Layout.setHorizontalGroup(
            pnlCap1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCap1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlCap1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblCap1Title)
                    .addComponent(lblCap1Desc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(10, Short.MAX_VALUE))
        );
        pnlCap1Layout.setVerticalGroup(
            pnlCap1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCap1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblCap1Title)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblCap1Desc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pnlCap2.setBackground(new java.awt.Color(255, 255, 255));
        pnlCap2.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        lblCap2Title.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        lblCap2Title.setText("INTERNAL STOCK MOVEMENTS");

        lblCap2Desc.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        lblCap2Desc.setForeground(new java.awt.Color(100, 116, 139));
        lblCap2Desc.setText("<html><div style='width:250px'>Coordinates inventory relocation via bin-to-bin transfers, stock splitting, cyclic count verification, and controlled scrap write-offs.</div></html>");

        javax.swing.GroupLayout pnlCap2Layout = new javax.swing.GroupLayout(pnlCap2);
        pnlCap2.setLayout(pnlCap2Layout);
        pnlCap2Layout.setHorizontalGroup(
            pnlCap2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCap2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlCap2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblCap2Title)
                    .addComponent(lblCap2Desc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(10, Short.MAX_VALUE))
        );
        pnlCap2Layout.setVerticalGroup(
            pnlCap2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCap2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblCap2Title)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblCap2Desc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pnlCap3.setBackground(new java.awt.Color(255, 255, 255));
        pnlCap3.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        lblCap3Title.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        lblCap3Title.setText("TRACEABILITY & LOCATION CONTROL");

        lblCap3Desc.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        lblCap3Desc.setForeground(new java.awt.Color(100, 116, 139));
        lblCap3Desc.setText("<html><div style='width:250px'>Maintains material attributes, organizes storage zones, defines specific storage bin capacities, and tracks individual item batch numbers.</div></html>");

        javax.swing.GroupLayout pnlCap3Layout = new javax.swing.GroupLayout(pnlCap3);
        pnlCap3.setLayout(pnlCap3Layout);
        pnlCap3Layout.setHorizontalGroup(
            pnlCap3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCap3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlCap3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblCap3Title)
                    .addComponent(lblCap3Desc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(10, Short.MAX_VALUE))
        );
        pnlCap3Layout.setVerticalGroup(
            pnlCap3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCap3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblCap3Title)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblCap3Desc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pnlCap4.setBackground(new java.awt.Color(255, 255, 255));
        pnlCap4.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        lblCap4Title.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        lblCap4Title.setText("OPERATIONAL REPORTING");

        lblCap4Desc.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        lblCap4Desc.setForeground(new java.awt.Color(100, 116, 139));
        lblCap4Desc.setText("<html><div style='width:250px'>Generates real-time summaries for daily activities, inventory valuations, stock aging trends, and warehouse space utilization levels.</div></html>");

        javax.swing.GroupLayout pnlCap4Layout = new javax.swing.GroupLayout(pnlCap4);
        pnlCap4.setLayout(pnlCap4Layout);
        pnlCap4Layout.setHorizontalGroup(
            pnlCap4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCap4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlCap4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblCap4Title)
                    .addComponent(lblCap4Desc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(10, Short.MAX_VALUE))
        );
        pnlCap4Layout.setVerticalGroup(
            pnlCap4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCap4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblCap4Title)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblCap4Desc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout pnlWelcomeLayout = new javax.swing.GroupLayout(pnlWelcome);
        pnlWelcome.setLayout(pnlWelcomeLayout);
        pnlWelcomeLayout.setHorizontalGroup(
            pnlWelcomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlWelcomeLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(pnlWelcomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel4)
                    .addComponent(btnWhatsNewToggle)
                    .addComponent(pnlWhatsNewContent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(61, 61, 61)
                .addGroup(pnlWelcomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(pnlCap1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlCap2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlCap3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlCap4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(37, 37, 37))
        );
        pnlWelcomeLayout.setVerticalGroup(
            pnlWelcomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlWelcomeLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jLabel1)
                .addGap(0, 0, 0)
                .addGroup(pnlWelcomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlWelcomeLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3)
                        .addGap(26, 26, 26)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnWhatsNewToggle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(pnlWhatsNewContent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlWelcomeLayout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(14, 14, 14)
                        .addComponent(pnlCap1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(pnlCap2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(pnlCap3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(pnlCap4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jMenuBar1.setMinimumSize(new java.awt.Dimension(70, 28));
        jMenuBar1.setPreferredSize(new java.awt.Dimension(70, 28));

        jMenu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/black-hamburger.png"))); // NOI18N

        jMenu2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/btnicn/help-14.png"))); // NOI18N
        jMenu2.setText("   Help       ");

        jMenuItem2.setText("User Manual");
        jMenu2.add(jMenuItem2);

        jMenuItem3.setText("Keyboard Shortcuts");
        jMenu2.add(jMenuItem3);

        jMenuItem4.setText("Contact Support");
        jMenu2.add(jMenuItem4);

        jMenuItem5.setText("About                                        ");
        jMenu2.add(jMenuItem5);

        jMenu1.add(jMenu2);

        mitemLogout.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_X, java.awt.event.InputEvent.ALT_DOWN_MASK | java.awt.event.InputEvent.CTRL_DOWN_MASK));
        mitemLogout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/btnicn/logout-16.png"))); // NOI18N
        mitemLogout.setText("   Logout       ");
        mitemLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mitemLogoutActionPerformed(evt);
            }
        });
        jMenu1.add(mitemLogout);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(cmbMovement, javax.swing.GroupLayout.PREFERRED_SIZE, 311, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnConfirm, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(451, 451, 451)
                        .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, 366, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnUser, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pnlWelcome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnConfirm, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbMovement, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnUser, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(pnlWelcome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void handleMovementSelection(String value) {

        if (!userSession.isValid()) {
            StatusMessageHandler.showError(txtStatus, "Session expired. Please login again!");
            // JOptionPane.showMessageDialog(this, "Session expired. Please login again.", "Session Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // movement permission mapping
        Map<String, String> movementToPermission = Map.ofEntries(
                Map.entry("md31", "VIEW_MATERIALS"),
                Map.entry("md32", "VIEW_MATERIALS"),
                Map.entry("md33", "VIEW_BINS"),
                Map.entry("md34", "VIEW_ZONES"),
                Map.entry("md35", "VIEW_VENDORS"),
                Map.entry("md36", "VIEW_CUSTOMERS"),
                Map.entry("md37", "VIEW_MATERIALS"),
                Map.entry("md38", "VIEW_USERS"),
                Map.entry("in11", "PROCESS_GR"),
                Map.entry("in12", "PROCESS_TRANSFER_IN"),
                Map.entry("in13", "PROCESS_GR_RETURNS"),
                Map.entry("out14", "PROCESS_GI"),
                Map.entry("out15", "PROCESS_GI"),
                Map.entry("out16", "PROCESS_GI_CONSUMPTION"),
                Map.entry("int17", "PROCESS_TRANSFER"),
                Map.entry("int18", "PROCESS_SPLITTING"),
                Map.entry("int19", "PROCESS_CYCLE_COUNT"),
                Map.entry("adj20", "PROCESS_ADJUSTMENT"),
                Map.entry("adj21", "PROCESS_SCRAP"),
                Map.entry("tr22", "PROCESS_PUTAWAY"),
                Map.entry("tr23", "PROCESS_PICKING"),
                Map.entry("tr24", "PROCESS_REPLENISHMENT"),
                Map.entry("inv51", "QUERY_INVENTORY"),
                Map.entry("inv52", "VIEW_STOCK_OVERVIEW"),
                Map.entry("inv53", "VIEW_BATCH_TRACKING"),
                Map.entry("inv54", "VIEW_STOCK_LEVEL"),
                Map.entry("inv55", "VIEW_EXPIRY_MONITOR"),
                Map.entry("inv56", "VIEW_INVENTORY_ALERTS"),
                Map.entry("rep61", "VIEW_DAILY_ACTIVITY_REPORT"),
                Map.entry("rep62", "VIEW_INVENTORY_VALUATION_REPORT"),
                Map.entry("rep63", "VIEW_STOCK_AGING_REPORT"),
                Map.entry("rep64", "VIEW_PERFORMANCE_REPORT"),
                Map.entry("rep65", "VIEW_UTILIZATION_REPORT"),
                Map.entry("rep66", "VIEW_FINANCIAL_REPORT")
        );

        // movement form mapping
        Map<String, Runnable> forms;
        forms = Map.ofEntries(
                Map.entry("md31", () -> new MaterialMasterForm().setVisible(true)),
                Map.entry("md32", () -> new BatchManagementForm().setVisible(true)),
                Map.entry("md33", () -> new BinManagementForm().setVisible(true)),
                Map.entry("md34", () -> new ZoneManagementForm().setVisible(true)),
                Map.entry("md35", () -> new VendorForm().setVisible(true)),
                Map.entry("md36", () -> new CustomerForm().setVisible(true)),
                Map.entry("md37", () -> new UOMForm().setVisible(true)),
                Map.entry("md38", () -> {
                    new UserManagementForm(userSession.getCurrentUser()).setVisible(true);
                }),
                Map.entry("in11", () -> new GRPurchaseOrderForm().setVisible(true)),
                Map.entry("in12", () -> new GRCustomerReturnsForm().setVisible(true)),
                Map.entry("in13", () -> new GRTransferInForm().setVisible(true)),
                Map.entry("out14", () -> new GISalesOrderForm().setVisible(true)),
                Map.entry("out15", () -> new ReturnToVendorForm().setVisible(true)),
                Map.entry("out16", () -> new GIInternalConsumptionForm().setVisible(true)),
                Map.entry("int17", () -> new BinToBinTransferForm().setVisible(true)),
                Map.entry("int18", () -> new SplittingPackBreakForm().setVisible(true)),
                Map.entry("int19", () -> new CycleCountForm().setVisible(true)),
                Map.entry("adj20", () -> new InventoryAdjustmentForm().setVisible(true)),
                Map.entry("adj21", () -> new ScrapWriteoffForm().setVisible(true)),
                Map.entry("tr22", () -> new PutawayTOForm().setVisible(true)),
                Map.entry("tr23", () -> new PickingTOForm().setVisible(true)),
                Map.entry("tr24", () -> new ReplenishmentTOForm().setVisible(true)),
                Map.entry("inv51", () -> new InventoryQueryForm().setVisible(true)),
                Map.entry("inv52", () -> new StockOverviewForm().setVisible(true)),
                Map.entry("inv53", () -> new BatchTrackingForm().setVisible(true)),
                Map.entry("inv54", () -> new StockLevelForm().setVisible(true)),
                Map.entry("inv55", () -> new ExpiryMonitorForm().setVisible(true)),
                Map.entry("inv56", () -> new InventoryAlertsForm().setVisible(true)),
                Map.entry("rep61", () -> new DailyActivityForm().setVisible(true)),
                Map.entry("rep62", () -> new InventoryValuationForm().setVisible(true)),
                Map.entry("rep63", () -> new StockAgingForm().setVisible(true)),
                Map.entry("rep64", () -> new PerformanceReportForm().setVisible(true)),
                Map.entry("rep65", () -> new UtilizationReportForm().setVisible(true)),
                Map.entry("rep66", () -> new FinancialReportForm().setVisible(true))
        );

        String code = value == null ? "" : value.trim().toLowerCase();

        boolean found = false;

        for (String key : forms.keySet()) {
            if (code.contains(key)) {

                String requiredPermission = movementToPermission.get(key);

                if (requiredPermission != null && !userSession.hasPermission(requiredPermission)) {
                    StatusMessageHandler.showWarning(txtStatus, "You do not have permission to access this feature!");
                    // JOptionPane.showMessageDialog(this, "You do not have permission to access this feature.", "Access Denied", JOptionPane.WARNING_MESSAGE);
                    return;
                }

                forms.get(key).run();
                found = true;
                break;
            }
        }

        if (!found) {
            StatusMessageHandler.showWarning(txtStatus, "No movement is defined for the entered code!");
            // JOptionPane.showMessageDialog(this, "No movement is defined for the entered code.\nPlease check and try again.", "Invalid Movement", JOptionPane.WARNING_MESSAGE);
        }
    }


    private void treeMovementMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_treeMovementMouseClicked
        // TODO add your handling code here:
        if (evt.getClickCount() == 2) {
            DefaultMutableTreeNode node = (DefaultMutableTreeNode) treeMovement.getLastSelectedPathComponent();

            if (node == null) {
                return;
            }

            if (node.isLeaf()) {
                String value = node.getUserObject().toString();
                handleMovementSelection(value);
            }

        }
    }//GEN-LAST:event_treeMovementMouseClicked

    private void mitemLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mitemLogoutActionPerformed
        // TODO add your handling code here:
        LogoutManager.logout();
    }//GEN-LAST:event_mitemLogoutActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        cmbMovement.requestFocusInWindow();
        getRootPane().setDefaultButton(btnConfirm);
    }//GEN-LAST:event_formWindowOpened

    private void btnConfirmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmActionPerformed
        // TODO add your handling code here:
        Object item = cmbMovement.getSelectedItem();
        String value = null;

        if (item != null) {
            value = item.toString().trim();
        }

        if (value == null || value.isEmpty()) {
            Object editorItem = cmbMovement.getEditor().getItem();
            if (editorItem != null) {
                value = editorItem.toString().trim();
            }
        }

        if (value == null || value.isEmpty()) {
            StatusMessageHandler.showWarning(txtStatus, "Please select or enter a movement!");
            cmbMovement.requestFocusInWindow();
            return;
        }

        handleMovementSelection(value);
    }//GEN-LAST:event_btnConfirmActionPerformed

    private void cmbMovementKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cmbMovementKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            btnConfirmActionPerformed(null);
        }
    }//GEN-LAST:event_cmbMovementKeyPressed

    private void btnUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUserActionPerformed
        // TODO add your handling code here:
        popupUserBtn.setSize(btnUser.getWidth(), btnUser.getHeight());
        popupUserBtn.show(btnUser, 0, btnUser.getHeight());
    }//GEN-LAST:event_btnUserActionPerformed

    private void menuitemLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuitemLogoutActionPerformed
        // TODO add your handling code here:
        LogoutManager.logout();
    }//GEN-LAST:event_menuitemLogoutActionPerformed

    private void btnWhatsNewToggleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnWhatsNewToggleActionPerformed
        boolean isVisible = pnlWhatsNewContent.isVisible();
        pnlWhatsNewContent.setVisible(!isVisible);
        pnlWelcome.revalidate();
        pnlWelcome.repaint();
    }//GEN-LAST:event_btnWhatsNewToggleActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConfirm;
    private javax.swing.JButton btnUser;
    private javax.swing.JButton btnWhatsNewToggle;
    private javax.swing.JComboBox<String> cmbMovement;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblCap1Desc;
    private javax.swing.JLabel lblCap1Title;
    private javax.swing.JLabel lblCap2Desc;
    private javax.swing.JLabel lblCap2Title;
    private javax.swing.JLabel lblCap3Desc;
    private javax.swing.JLabel lblCap3Title;
    private javax.swing.JLabel lblCap4Desc;
    private javax.swing.JLabel lblCap4Title;
    private javax.swing.JLabel lblUpdate1Desc;
    private javax.swing.JLabel lblUpdate1Title;
    private javax.swing.JLabel lblUpdate2Desc;
    private javax.swing.JLabel lblUpdate2Title;
    private javax.swing.JLabel lblUpdate3Desc;
    private javax.swing.JLabel lblUpdate3Title;
    private javax.swing.JMenuItem menuitemLogout;
    private javax.swing.JMenuItem mitemLogout;
    private javax.swing.JPanel pnlCap1;
    private javax.swing.JPanel pnlCap2;
    private javax.swing.JPanel pnlCap3;
    private javax.swing.JPanel pnlCap4;
    private javax.swing.JPanel pnlWelcome;
    private javax.swing.JPanel pnlWhatsNewContent;
    private javax.swing.JPopupMenu popupUserBtn;
    private javax.swing.JTree treeMovement;
    private javax.swing.JLabel txtStatus;
    // End of variables declaration//GEN-END:variables
}
