/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package ui.dialogs;

import javax.swing.ImageIcon;

/**
 *
 * @author Sanod
 */
public class PasswordEntryForm extends javax.swing.JDialog {

    private String result = null;
    private char defaultEchoChar;

    /**
     * Creates new form PasswordEntryForm
     */
    public PasswordEntryForm(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setLocationRelativeTo(null);
        setIconImage(new ImageIcon(getClass().getResource("/icons/app-icon.png")).getImage());
        
        defaultEchoChar = txtPassword.getEchoChar();
        
        setupFieldNavigation();
    }

    public void setTitle(String title) {
        lblTitle.setText(title);
    }

    public String getResult() {
        return result;
    }
    
    private void setupFieldNavigation() {
        
        javax.swing.JPasswordField[] passwordFields = {txtPassword, txtConfirmPassword};

        for (int i = 0; i < passwordFields.length; i++) {
            final int currentIndex = i;
            passwordFields[i].addKeyListener(new java.awt.event.KeyAdapter() {
                @Override
                public void keyPressed(java.awt.event.KeyEvent evt) {
                    if (evt.getKeyCode() == java.awt.event.KeyEvent.VK_DOWN) {
                        evt.consume();
                        if (currentIndex < passwordFields.length - 1) {
                            passwordFields[currentIndex + 1].requestFocus();
                        }
                    } else if (evt.getKeyCode() == java.awt.event.KeyEvent.VK_UP) {
                        evt.consume();
                        if (currentIndex > 0) {
                            passwordFields[currentIndex - 1].requestFocus();
                        }
                    }
                }
            });
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtPassword = new javax.swing.JPasswordField();
        jLabel3 = new javax.swing.JLabel();
        txtConfirmPassword = new javax.swing.JPasswordField();
        jLabel4 = new javax.swing.JLabel();
        btnOK = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        tglbtnShowConfirmPwd = new javax.swing.JToggleButton();
        tglbtnShowPwd = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setIconImage(new ImageIcon(getClass().getResource("/icons/app-icon.png")).getImage());
        setResizable(false);
        setType(java.awt.Window.Type.POPUP);

        lblTitle.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle.setText("Enter Password");

        jLabel2.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        jLabel2.setText("Password *");

        jLabel3.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        jLabel3.setText("Confirm *");

        jLabel4.setFont(new java.awt.Font("Segoe UI Semibold", 0, 10)); // NOI18N
        jLabel4.setText("Min 8 chars: upper, lower, number, special");

        btnOK.setText("OK");
        btnOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOKActionPerformed(evt);
            }
        });

        btnCancel.setText("Cancel");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        tglbtnShowConfirmPwd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/btnicn/view-14.png"))); // NOI18N
        tglbtnShowConfirmPwd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tglbtnShowConfirmPwdActionPerformed(evt);
            }
        });

        tglbtnShowPwd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/btnicn/view-14.png"))); // NOI18N
        tglbtnShowPwd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tglbtnShowPwdActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel4)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel2)
                                        .addComponent(jLabel3))
                                    .addGap(29, 29, 29)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(txtPassword)
                                        .addComponent(txtConfirmPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(77, 77, 77)
                                .addComponent(btnOK)
                                .addGap(18, 18, 18)
                                .addComponent(btnCancel)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tglbtnShowConfirmPwd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tglbtnShowPwd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(24, 24, 24))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(lblTitle)
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel3)
                                .addComponent(txtConfirmPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(tglbtnShowConfirmPwd))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnOK)
                            .addComponent(btnCancel)))
                    .addComponent(tglbtnShowPwd))
                .addContainerGap(29, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOKActionPerformed
        // TODO add your handling code here:
        String password = new String(txtPassword.getPassword());
        String confirm = new String(txtConfirmPassword.getPassword());

        if (password.isEmpty() || confirm.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "Both fields are required.", "Validation", javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }

        if (!password.equals(confirm)) {
            javax.swing.JOptionPane.showMessageDialog(this, "Passwords do not match.", "Validation", javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }

        // validate complexity
        core.security.UserAuthentication auth = new core.security.UserAuthentication();
        if (!auth.validatePasswordComplexity(password)) {
            javax.swing.JOptionPane.showMessageDialog(this, "Password must be at least 8 characters and contain:\n- Uppercase letter\n- Lowercase letter\n- Number\n- Special character", "Validation", javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }

        result = password;
        dispose();
    }//GEN-LAST:event_btnOKActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        // TODO add your handling code here:
        result = null;
        dispose();
    }//GEN-LAST:event_btnCancelActionPerformed

    private void tglbtnShowConfirmPwdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tglbtnShowConfirmPwdActionPerformed
        // TODO add your handling code here:
        if (tglbtnShowConfirmPwd.isSelected()) {
            // show pwd
            txtConfirmPassword.setEchoChar((char) 0);
            tglbtnShowConfirmPwd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/btnicn/hide-14.png")));
        } else {
            // hide pwd
            txtConfirmPassword.setEchoChar(defaultEchoChar);
            tglbtnShowConfirmPwd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/btnicn/view-14.png")));
        }
    }//GEN-LAST:event_tglbtnShowConfirmPwdActionPerformed

    private void tglbtnShowPwdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tglbtnShowPwdActionPerformed
        // TODO add your handling code here:
        if (tglbtnShowPwd.isSelected()) {
            // show pwd
            txtPassword.setEchoChar((char) 0);
            tglbtnShowPwd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/btnicn/hide-14.png")));
        } else {
            // hide pwd
            txtPassword.setEchoChar(defaultEchoChar);
            tglbtnShowPwd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/btnicn/view-14.png")));
        }
    }//GEN-LAST:event_tglbtnShowPwdActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PasswordEntryForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PasswordEntryForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PasswordEntryForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PasswordEntryForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                PasswordEntryForm dialog = new PasswordEntryForm(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnOK;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JToggleButton tglbtnShowConfirmPwd;
    private javax.swing.JToggleButton tglbtnShowPwd;
    private javax.swing.JPasswordField txtConfirmPassword;
    private javax.swing.JPasswordField txtPassword;
    // End of variables declaration//GEN-END:variables
}
